# Generated by Django 4.0.6 on 2022-07-11 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrashKinds',
            fields=[
                ('trash_kind', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('trash_way', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('user_pw', models.CharField(max_length=30)),
                ('user_alias', models.CharField(max_length=30)),
                ('user_pw_hash', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trash_img', models.ImageField(max_length=200, upload_to='')),
                ('img_upload_date', models.DateTimeField(max_length=30)),
                ('img_upload_time', models.DateTimeField(max_length=30)),
                ('trash_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HowTrash.user')),
                ('trash_kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HowTrash.trashkinds')),
            ],
        ),
    ]
