# Generated by Django 4.0.6 on 2022-07-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trashkinds',
            fields=[
                ('trash_kind', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('trash_throw_way', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'TrashKinds',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Uploadedimg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_img', models.CharField(max_length=200)),
                ('upload_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'UploadedImg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20, unique=True)),
                ('user_alias', models.CharField(max_length=20, unique=True)),
                ('user_pw', models.CharField(max_length=64)),
                ('user_email', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
    ]
