<<<<<<< HEAD
# Generated by Django 4.0.6 on 2022-08-03 23:46
=======
# Generated by Django 4.0.6 on 2022-08-04 00:23
>>>>>>> 38-BE-elastic_search_err_handler

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
