# Generated by Django 4.0.6 on 2022-07-26 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rebikeuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='trash',
            fields=[
                ('trash_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_on_basket', models.BooleanField(default=False)),
                ('img', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trash_kind', models.CharField(max_length=20)),
                ('owner', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='rebikeuser.user')),
            ],
            options={
                'db_table': 'trash',
            },
        ),
    ]
