# Generated by Django 4.0.6 on 2022-07-23 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rebikeuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='challenge',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'challenge',
            },
        ),
        migrations.CreateModel(
            name='trash_kind',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('way', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'trash_kind',
            },
        ),
        migrations.CreateModel(
            name='user_challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge_number', models.ForeignKey(db_column='challenge_number', on_delete=django.db.models.deletion.CASCADE, to='rebiketrash.challenge')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='rebikeuser.user')),
            ],
            options={
                'db_table': 'user_challenge',
            },
        ),
        migrations.CreateModel(
            name='uploaded_trash_image',
            fields=[
                ('uploaded_trash_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.IntegerField(default=1)),
                ('img', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trash_kind', models.ForeignKey(db_column='trash_kind', on_delete=django.db.models.deletion.CASCADE, to='rebiketrash.trash_kind')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='rebikeuser.user')),
            ],
            options={
                'db_table': 'uploaded_trash_image',
            },
        ),
    ]
