# Generated by Django 4.0.6 on 2022-07-20 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rebikeuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='trash_kind',
            fields=[
                ('kind', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('way', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'trash_kind',
            },
        ),
        migrations.CreateModel(
            name='uploaded_trash_image',
            fields=[
                ('uploaded_trash_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.IntegerField(default=1)),
                ('img', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('trash_kind', models.ForeignKey(db_column='trash_kind', on_delete=django.db.models.deletion.CASCADE, to='rebiketrash.trash_kind')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='rebikeuser.user')),
            ],
            options={
                'db_table': 'uploaded_trash_image',
            },
        ),
    ]
