# Generated by Django 4.0.6 on 2022-07-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebiketrash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='trash_kind',
            fields=[
                ('kind', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('way', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'trash_kind',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='uploaded_trash_image',
            fields=[
                ('uploaded_trash_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'uploaded_trash_image',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Trashkinds',
        ),
        migrations.DeleteModel(
            name='Uploadedtrash',
        ),
    ]
