# Generated by Django 4.0.6 on 2022-07-31 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rebikeuser', '0001_initial'),
        ('rebiketrash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='trash_image',
            fields=[
                ('trash_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.IntegerField(default=1)),
                ('image', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='rebikeuser.user')),
            ],
            options={
                'db_table': 'trash_image',
            },
        ),
        migrations.CreateModel(
            name='trash_kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trash_image_id', models.ForeignKey(db_column='trash_image_id', on_delete=django.db.models.deletion.CASCADE, to='rebiketrash.trash_image')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='rebikeuser.user')),
            ],
            options={
                'db_table': 'trash_kind',
            },
        ),
        migrations.DeleteModel(
            name='uploaded_trash_image',
        ),
    ]
