# Generated by Django 4.0.6 on 2022-07-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebiketrash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trash_kind',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='uploaded_trash_image',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
