# Generated by Django 4.0.6 on 2022-07-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebiketrash', '0002_alter_uploaded_trash_image_trash_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaded_trash_image',
            name='trash_kind',
            field=models.CharField(max_length=200),
        ),
    ]
