# Generated by Django 4.0.6 on 2022-07-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebiketrash', '0003_alter_uploaded_trash_image_trash_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaded_trash_image',
            name='trash_kind',
            field=models.CharField(max_length=300),
        ),
    ]
