# Generated by Django 4.0.6 on 2022-07-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20, unique=True)),
                ('user_alias', models.CharField(max_length=20, unique=True)),
                ('user_pw', models.CharField(max_length=64)),
                ('user_email', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
    ]
