# Generated by Django 4.0.6 on 2022-07-14 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rebikeuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
